package woftracker.record;

import java.util.PriorityQueue;
import javax.swing.JTextPane;
import javax.swing.BorderFactory;
import javax.swing.border.*;
import java.awt.Color;

public interface Recordable {
	String DATE_ID = "EL DATEY GOES HERE";
	String INITIAL_TEXT =
	"<html><head><title>WOF Recap: " + DATE_ID + "</title><style type = \"text/css\">" +
		"span { font-family: Verdana; font-size: 12pt; }" +
		"span.solve { color: #4444AB; }" +
		"span.epic { color: #228B22; }" +
		"span.fail { color: #AB4444; }" +
		"span.strength { color: #8B8B8B; font-size: 10pt; }" +
	"</style></head><body><br>" +
	"<span><font color=#90989F><i>This is an unofficial recap of America's Game.</i><br>" +
	"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</font></span><br><br><br>";
	
	String END_TEXT = "<br><span><font color=#90989F>~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~<br><br>" +
	"<i>This HTML file was generated by the WOF Tracker Java Program, created by Wayoshi.</i></font></span><br><br>";	//©
	
	StringBuilder GAME_TEXT = new StringBuilder(INITIAL_TEXT);
	String CLOSING_TAGS = "</body></html>";
	
	JTextPane RECAP_BOX = new JTextPane();	//RecordPanel.updatePreview()
	
	Color RED_COLOR = new Color(255, 133, 133), YELLOW_COLOR = new Color(255, 255, 133), BLUE_COLOR = new Color(133, 133, 255);
	
	String CAT_ID = "CATEGORYn";
	String PB_ID = "PUZZLEBOARD #";
	String PP_ID = "PRIZEPUZZLEn&c";
	String VEHICLE_ID = "VEHICLEn&c";
}